package com.ikverse.egxanalyzer.data

import android.content.ContentValues
import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper
import com.ikverse.egxanalyzer.model.PositionStatus
import com.ikverse.egxanalyzer.model.TradeState
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment

/**
 * That what the user has been told survives a restart, and that gaining the table costs no trades.
 *
 * The record of what was said is the whole basis of a notification about a *change*: lose it and
 * the next sweep sees every trade for the first time, which announces nothing at all and then
 * announces the next thing twice if it comes back wrong. The migration half matters for the reason
 * [LocalDataStoreMigrationTest] gives - a fresh install builds the table correctly every time, so a
 * bad version bump only ever shows up on a phone that has been running the app for months.
 */
@RunWith(RobolectricTestRunner::class)
class TradeStatusStoreTest {

    private val context: Context get() = RuntimeEnvironment.getApplication()

    @Test
    fun `a state comes back exactly as it went in`() {
        val store = LocalDataStore(context)
        val seen = mapOf(
            "AMOC@2026-08-03" to TradeState(PositionStatus.STOPPED_OUT, open = false),
            "SWDY@2026-08-03" to TradeState(PositionStatus.PARTIAL_TARGET_HIT, open = true),
        )

        store.savePositionStatusSeen(seen)

        assertEquals(seen, store.positionStatusSeen())
    }

    @Test
    fun `a trade that has gone takes its row with it and leaves the others`() {
        val store = LocalDataStore(context)
        store.savePositionStatusSeen(
            mapOf(
                "AMOC@2026-08-03" to TradeState(PositionStatus.OPEN, open = true),
                "SWDY@2026-08-03" to TradeState(PositionStatus.OPEN, open = true),
            ),
        )

        store.savePositionStatusSeen(emptyMap(), forgotten = setOf("AMOC@2026-08-03"))

        assertEquals(setOf("SWDY@2026-08-03"), store.positionStatusSeen().keys)
    }

    @Test
    fun `a status this build cannot read is dropped rather than taking the sweep down`() {
        // Written by a build that knows a state this one does not. Dropping the row makes the trade
        // look new, which records where it stands and says nothing - the right answer to a row this
        // version cannot interpret, and better than a crash inside a background sweep.
        val store = LocalDataStore(context)
        store.savePositionStatusSeen(
            mapOf("SWDY@2026-08-03" to TradeState(PositionStatus.OPEN, open = true)),
        )
        store.writableDatabase.insert(
            "position_status_seen",
            null,
            ContentValues().apply {
                put("position_id", "AMOC@2026-08-03")
                put("status", "TAKEN_OVER")
                put("open", 0)
                put("at", 1_760_000_000_000)
            },
        )

        assertEquals(setOf("SWDY@2026-08-03"), store.positionStatusSeen().keys)
    }

    @Test
    fun `a phone that had trades before this table existed keeps them and gains it`() {
        Version17(context).writableDatabase.use { old ->
            old.insert("positions", null, version17Position())
        }

        val store = LocalDataStore(context)

        // The upgrade added a table; it must not have cost the record that was already there.
        assertEquals("AMOC@2026-07-20", store.positions().single().id)
        assertTrue(store.positionStatusSeen().isEmpty())
        store.savePositionStatusSeen(
            mapOf("AMOC@2026-07-20" to TradeState(PositionStatus.OPEN, open = true)),
        )
        assertEquals(
            TradeState(PositionStatus.OPEN, open = true),
            store.positionStatusSeen().getValue("AMOC@2026-07-20"),
        )
    }

    private fun version17Position() = ContentValues().apply {
        put("id", "AMOC@2026-07-20")
        put("ticker", "AMOC")
        put("recommendation_date", "2026-07-20")
        put("entry_price", 10.5)
        put("entry_date", "2026-07-21")
        put("window_sessions", 10)
        put("opened_at", 1_753_000_000_000)
        put("updated_at", 1_753_000_000_000)
        put("updated_by", "phone")
        put("deleted", 0)
    }

    /**
     * The database as version 17 left it, which is the version every phone is on before this one.
     *
     * Only the table this test needs to find intact afterwards, and spelled out here rather than
     * taken from today's code: a migration test whose "old" shape is generated by the new code
     * tests nothing, because both sides move together.
     */
    private class Version17(context: Context) :
        SQLiteOpenHelper(context, LocalDataStore.DATABASE_NAME, null, 17) {

        override fun onCreate(db: SQLiteDatabase) {
            db.execSQL(
                """CREATE TABLE IF NOT EXISTS positions (
                    id TEXT PRIMARY KEY,
                    ticker TEXT NOT NULL,
                    name_en TEXT,
                    name_ar TEXT,
                    channel TEXT,
                    recommendation_date TEXT NOT NULL,
                    entry_price REAL NOT NULL,
                    entry_date TEXT NOT NULL,
                    exit_price REAL,
                    exit_date TEXT,
                    closed_manually INTEGER NOT NULL DEFAULT 0,
                    entry_low REAL,
                    entry_high REAL,
                    target1 REAL,
                    target2 REAL,
                    stop_loss REAL,
                    window_sessions INTEGER NOT NULL,
                    window_custom INTEGER NOT NULL DEFAULT 0,
                    keep_open INTEGER NOT NULL DEFAULT 0,
                    keep_open_note TEXT,
                    unknown TEXT NOT NULL DEFAULT '{}',
                    opened_at INTEGER NOT NULL DEFAULT 0,
                    updated_at INTEGER NOT NULL DEFAULT 0,
                    updated_by TEXT NOT NULL DEFAULT '',
                    deleted INTEGER NOT NULL DEFAULT 0
                )""",
            )
        }

        override fun onUpgrade(db: SQLiteDatabase, oldVersion: Int, newVersion: Int) = Unit
    }
}
